import requests

r = requests.get(url="http://192.168.1.180/json/state").json()

ccnf = r['ccnf']
nl = r['nl']
udpn = r['udpn']
seg = r['seg'][0]

on = r['on']
bri = r['bri']
transition = r['transition']
ps = r['ps']
pl = r['pl']
ccnf_min = ccnf['min']
ccnf_max = ccnf['max']
ccnf_time = ccnf['time']
nl_on = nl['on']
nl_dur = nl['dur']
nl_fade = nl['fade']
nl_mode = nl['mode']
nl_tbri = nl['tbri']
nl_rem = nl['rem']
udpn_send = udpn['send']
udpn_recv = udpn['recv']
lor = r['lor']
mainseg = r['mainseg']
seg_id = seg['id']
seg_start = seg['start']
seg_stop = seg['stop']
seg_len = seg['len']
seg_grp = seg['grp']
seg_spc =seg['spc']
seg_on = seg['id']
seg_bri = seg['bri']
seg_col = seg['col']
fx = seg['fx']
sx = seg['sx']
ix = seg['ix']
pal = seg['pal']
sel = seg['sel']
rev = seg['rev']
mi = seg['mi']


